//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-94A2BA9\\SQLEXPRESS;Initial Catalog=CH_DIENTHOAIDIDONG_LinQ;Us" +
            "er ID=sa;Password=sa2012")]
        public string CH_DIENTHOAIDIDONG_LinQConnectionString {
            get {
                return ((string)(this["CH_DIENTHOAIDIDONG_LinQConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-94A2BA9\\SQLEXPRESS;Initial Catalog=CH_DIENTHOAIDIDONG_LinQ;Pe" +
            "rsist Security Info=True;User ID=sa;Password=sa2012")]
        public string CH_DIENTHOAIDIDONG_LinQConnectionString1 {
            get {
                return ((string)(this["CH_DIENTHOAIDIDONG_LinQConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-57HIP66\\SQLEXPRESS;Initial Catalog=CH_DIENTHOAIDIDONG_LinQ;Us" +
            "er ID=sa;Password=sa2012")]
        public string CH_DIENTHOAIDIDONG_LinQConnectionString2 {
            get {
                return ((string)(this["CH_DIENTHOAIDIDONG_LinQConnectionString2"]));
            }
        }
    }
}
